const express = require('express')
const app = express()
const AuthRouter = require('./routes/AuthRoute')
const ProductRouter = require('./routes/ProductRoute')
const CartRouter = require('./routes/CartRoute')
const CategoryRouter = require('./routes/CategoryRoute')
const SubCategoryRouter = require('./routes/SubCategoryRoute')
const AddressRouter = require('./routes/AddressRoute')
const OrderRouter = require('./routes/OrderRoute')

app.use(express.json())
app.use('/auth', AuthRouter)
app.use('/product', ProductRouter)
app.use('/cart',CartRouter)
app.use('/category',CategoryRouter)
app.use('/subcategory',SubCategoryRouter)
app.use('/address',AddressRouter)
app.use('/order',OrderRouter)

module.exports = app